[Settings]
user_name = S.Elin
password = 07041994
SOC_id = 1655374

[Roles]
# if you want to apply/remove overrides and then verify them, use "OAC,OAV"
# if you want ONLY to apply/remove overrides, use "OAC"
# if the overrides have been already appied/removed, and you want to verify only, use "OAV"
# NO SPACES AFTER COMMAS!!!
SOC_roles = OAC,OAV